### ISSUE TITLE
During handling of the above exception, another exception occurred

### ISSUE THREAD

**Issue by davidluan** [JimCurryWang/python-shopee#10]
![image](https://user-images.githubusercontent.com/36660448/52191539-1b45e080-2880-11e9-9358-215a8a1cbd18.png)

My Python code suddenly hang and I press Ctrl + C force close, it show the error in above. 
I not sure what is the error message is this and how to prevent it.

**Comment by JimCurryWang** [comment]
May I know what is your input for ordersn_list?

**Comment by davidluan** [comment]
resp = client.order.get_order_by_status(order_status="READY_TO_SHIP")
orderID = resp["orders"][x]["ordersn"]
orderName = client.order.get_order_detail(ordersn_list = [orderID] )

**Comment by JimCurryWang** [comment]
Hi David,
Here is an example for ordersn_list , note that is should be a list of string and no more than 50 orders in a batch.

```python 
# get_order_detail
ordersn_list = [ '1712071633982A7','1712071632981JW','171207163097YCJ']
resp = client.order.get_order_detail(ordersn_list = ordersn_list )
print(resp)
```

**Comment by davidluan** [comment]
resp = client.order.get_order_by_status(order_status="READY_TO_SHIP")

for x in range(len(resp["orders"])):
    orderID = resp["orders"][x]["ordersn"]
    print('Order ID for order %d is %s' %(x,orderID))
    orderName = client.order.get_order_detail(ordersn_list = [orderID] )
    itemName = orderName["orders"][0]["items"][0]["item_name"]
    print(itemName)

currently my code is look like above
I use the for loop. Or I need save my orderID to an array as the example you show me?

**Comment by JimCurryWang** [comment]
@davidluan  
I think it is worth to have a try, hence, there has some rate limit in API calls.

By the way, i have also retested the ``get_order_detail`` method and it would fine to me.

**Comment by davidluan** [comment]
yes, actually the get_order_detail method can work. 
This error message not always pop out. I run my code for around 10 days, It only occurred 2 times and I does not know how to fix it. 
When this error occurs, my code will hang there and do nothing until I force close.

**Comment by JimCurryWang** [comment]
Uhm... I guess it was because of internal server error. 

I have added a 10s timeout condition as the requests params.  13d3532

Hope it could work!

**Comment by davidluan** [comment]
Okay, thanks! I will update it now.
For the ordersn_list the maximum number is only 50 order right? How if I have more than 50 order ?

**Comment by JimCurryWang** [comment]
I will use a for loop if the orders over 50 limitations.

**Comment by davidluan** [comment]
okay, noted with thanks!
