### ISSUE TITLE
getting code for token request

### ISSUE THREAD

**Issue by Qr4cl3** [JimCurryWang/python-shopee#44]
Every time, when getting a code, the program will pop up firefox for authentication with username and password. 
Then, use that code to get a token.
From API Docs, the coding has 10 minutes lifetime. 
That means we have to request a new code every 10 mins.
How could it be automatic if we have to manually fill in username and password for every 10 mins in the browser?

**Comment by tjengbudi** [comment]
@Qr4cl3 the code just to request accesstoken. if you maintain the access code well, you will not need to get code and fill the user and password again
