### ISSUE TITLE
New OpenAPI Release

### ISSUE THREAD

**Issue by romeojuliets** [JimCurryWang/python-shopee#5]
There have significant openAPI updates that seems not included in the latest version.

- payment.GetPaymentList :  fetch the supported payment method list by country

**Comment by JimCurryWang** [comment]
Thanks for the notice, 
you can find the function in ``client.public.get_payment_list`` right now.


```python
import pyshopee

client = pyshopee.Client( shopid, partnerid, API_key )

# country : ID/MY/SG/VN/PH/TH/TW
resp = client.public.get_payment_list(country="TW")
print(resp)
```

**Comment by romeojuliets** [comment]
@JimCurryWang , Thanks for the help.
